

INSERT INTO dnd.language (id, name) VALUES (1, 'All');
INSERT INTO dnd.language (id, name) VALUES (2, 'Auran');
INSERT INTO dnd.language (id, name) VALUES (3, 'Understands Abyssal but can''t speak  it');
INSERT INTO dnd.language (id, name) VALUES (4, 'Telepathy 60 ft.');
INSERT INTO dnd.language (id, name) VALUES (5, 'Infernal but can''t speak');
INSERT INTO dnd.language (id, name) VALUES (6, 'Worg');
INSERT INTO dnd.language (id, name) VALUES (7, 'Goblin');
INSERT INTO dnd.language (id, name) VALUES (8, 'Understands Common but can''t speak  it');
INSERT INTO dnd.language (id, name) VALUES (9, 'Thieves'' cant plus any two languages');
INSERT INTO dnd.language (id, name) VALUES (10, 'Yeti');
INSERT INTO dnd.language (id, name) VALUES (11, 'Draconic');
INSERT INTO dnd.language (id, name) VALUES (12, 'Any one language');
INSERT INTO dnd.language (id, name) VALUES (13, 'Common (can''t speak in rat form)');
INSERT INTO dnd.language (id, name) VALUES (14, 'Common (can''t speak in boar form)');
INSERT INTO dnd.language (id, name) VALUES (15, 'Sahuagin');
INSERT INTO dnd.language (id, name) VALUES (16, 'Understands Draconic but can''t speak  it');
INSERT INTO dnd.language (id, name) VALUES (17, '--');
INSERT INTO dnd.language (id, name) VALUES (18, 'Common (can''t speak in bear form)');
INSERT INTO dnd.language (id, name) VALUES (19, 'Telepathy 120 ft. but can''t speak');
INSERT INTO dnd.language (id, name) VALUES (20, 'Understands the languages of its creator but can''t speak');
INSERT INTO dnd.language (id, name) VALUES (21, 'The languages it knew in life');
INSERT INTO dnd.language (id, name) VALUES (22, 'Understands Deep Speech but can''t speak');
INSERT INTO dnd.language (id, name) VALUES (23, 'Ignan');
INSERT INTO dnd.language (id, name) VALUES (24, 'Understands Infernal but can''t speak it');
INSERT INTO dnd.language (id, name) VALUES (25, 'Common plus up to five other languages');
INSERT INTO dnd.language (id, name) VALUES (26, 'Druidic');
INSERT INTO dnd.language (id, name) VALUES (27, 'Common');
INSERT INTO dnd.language (id, name) VALUES (28, 'One language known by its creator');
INSERT INTO dnd.language (id, name) VALUES (29, 'Auran but can''t speak them');
INSERT INTO dnd.language (id, name) VALUES (30, 'Giant Elk');
INSERT INTO dnd.language (id, name) VALUES (31, 'Understands commands given in any language but can''t speak');
INSERT INTO dnd.language (id, name) VALUES (32, 'Dwarvish');
INSERT INTO dnd.language (id, name) VALUES (33, 'Primordial');
INSERT INTO dnd.language (id, name) VALUES (34, 'Giant');
INSERT INTO dnd.language (id, name) VALUES (35, 'Common (can''t speak in tiger form)');
INSERT INTO dnd.language (id, name) VALUES (36, 'Any four languages');
INSERT INTO dnd.language (id, name) VALUES (37, 'Any languages it knew in life');
INSERT INTO dnd.language (id, name) VALUES (38, 'Orc');
INSERT INTO dnd.language (id, name) VALUES (39, 'Sylvan');
INSERT INTO dnd.language (id, name) VALUES (40, 'Sylvan but can''t speak them');
INSERT INTO dnd.language (id, name) VALUES (41, 'Sylvan but can''t speak');
INSERT INTO dnd.language (id, name) VALUES (42, 'Draconic but can''t speak them');
INSERT INTO dnd.language (id, name) VALUES (43, 'Common understands but canât speak');
INSERT INTO dnd.language (id, name) VALUES (44, 'Giant Owl');
INSERT INTO dnd.language (id, name) VALUES (45, 'Gnoll');
INSERT INTO dnd.language (id, name) VALUES (46, 'Auran  Understands Common but doesn''t speak it');
INSERT INTO dnd.language (id, name) VALUES (47, 'Aquan');
INSERT INTO dnd.language (id, name) VALUES (48, 'Infernal');
INSERT INTO dnd.language (id, name) VALUES (49, 'Any six languages');
INSERT INTO dnd.language (id, name) VALUES (50, 'Giant but can''t speak  them');
INSERT INTO dnd.language (id, name) VALUES (51, 'Winter Wolf');
INSERT INTO dnd.language (id, name) VALUES (52, 'Any one language (usually Common)');
INSERT INTO dnd.language (id, name) VALUES (53, 'Terran');
INSERT INTO dnd.language (id, name) VALUES (54, 'Understands all languages it knew in life but can''t speak');
INSERT INTO dnd.language (id, name) VALUES (55, 'Gnomish');
INSERT INTO dnd.language (id, name) VALUES (56, 'Elvish');
INSERT INTO dnd.language (id, name) VALUES (57, 'Otyugh');
INSERT INTO dnd.language (id, name) VALUES (58, 'Deep Speech');
INSERT INTO dnd.language (id, name) VALUES (59, 'Common (can''t speak in wolf form)');
INSERT INTO dnd.language (id, name) VALUES (60, 'Understands Common');
INSERT INTO dnd.language (id, name) VALUES (61, 'Abyssal');
INSERT INTO dnd.language (id, name) VALUES (62, 'Giant Eagle  understands Common');
INSERT INTO dnd.language (id, name) VALUES (63, 'Blink Dog  Understands Sylvan but can''t speak it');
INSERT INTO dnd.language (id, name) VALUES (64, 'Telepathy 120 ft.');
INSERT INTO dnd.language (id, name) VALUES (65, 'Any two languages');
INSERT INTO dnd.language (id, name) VALUES (66, 'Sphinx');
INSERT INTO dnd.language (id, name) VALUES (67, 'Druidic plus any two languages');
INSERT INTO dnd.language (id, name) VALUES (68, 'Undercommon');
INSERT INTO dnd.language (id, name) VALUES (69, 'Celestial');

