spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=adventure_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      monster: monster
      monster-group: monster-group
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.hibernate.default_schema: adventure_service
server:
  port : 8083
